package com.wyh.dao;

import com.wyh.entity.test;

public interface testMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Dec 22 17:28:39 CST 2016
     */
    int insert(test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Dec 22 17:28:39 CST 2016
     */
    int insertSelective(test record);
}