package com.wyh.entity;

import com.wyh.common.BaseEntity;

public class Test extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.s
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    private String s;

    public Test(Integer id, String name, String s) {
        this.id = id;
        this.name = name;
        this.s = s;
    }

    public Test() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.s
     *
     * @return the value of test.s
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    public String getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.s
     *
     * @param s the value for test.s
     *
     * @mbggenerated Mon Dec 26 17:11:26 CST 2016
     */
    public void setS(String s) {
        this.s = s == null ? null : s.trim();
    }
}